// react-app/src/elements/components/Search.js
import React from 'react';
import '../../css/components/Search.css';

const Search = () => {
    return (
        <div className='search'>
            <form className='search__form' id='search' action='#' method='get'>
                <input className='search__form--input' name='search' type='text' placeholder='Search...' />
                <button className='search__form--button' type='submit'></button>
            </form>
        </div>
    );
  }

export default Search;

// angular-app/src/app/search/search.component.ts
import { Component, Input } from '@angular/core';


@Component({
    selector: 'search',
    templateUrl: './search.component.html',
    styleUrls: ['./search.component.css' ]
})
export class SearchComponent {
    constructor() { }
}

<div class='search'>
    <form class='search__form' id='search'  action='#' method='get'>
      <input  class='search__form--input'
              name='search'
              type='text'
              placeholder='Search...'>
      <button class='search__form--button' type='submit'></button>
    </form>
  </div>
