// react-app/src/elements/components/SupportBar.js
import React from 'react';
import '../../css/components/SupportBar.css';

const SupportBar = () => {
    const options = ['+0123 45 67 89', 'support@cart.com', 'Live Chat'].map( (option) => <div className="options__container col row ml-auto"><a href="">{option}</a></div> );
    const languages = ['FIN', 'ENG'].map( (language) => <li>{language}</li> );
    const language = 'ENG';
    const currencies = ['USD', 'AUD', 'GBP', 'EUR'].map( (currency) => <option>{currency}</option> );
    return (
        <div className="bar">
            <div className="support__bar">
                <div className="bar__content container clear-fix row">
                    <div className="bar__content--left col row">
                        <div className="language">
                            <div className="menu__dropdown">
                                <a data-toggle="dropdown" href="">{language}</a>
                                <span className="dropdown-toggle"></span>
                                <ul className="menu__dropdown--list">
                                    {languages}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div className="bar__content--right row">
                        <div className="options ml-auto row">
                            {options}
                        </div>
                        <div className="currency ml-auto">
                            <select className="currency__select">
                                {currencies}
                            </select>
                            <span className="currency__span--toggle"></span>
                        </div>
                        <div className="help ml-auto">
                            <button className="help__button">Customer Center</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
  }

export default SupportBar;

// angular-app/src/app/supportbar/supportbar.component.ts
import { Component, Input } from '@angular/core';

@Component({
    selector: 'supportbar',
    templateUrl: './supportbar.component.html',
    styleUrls: ['./supportbar.component.css' ]
})
export class SupportBarComponent {
    options:Array<any> = [];
    languages:Array<any> = [];
    currencies:Array<any> = [];
    constructor (){
        this.options= ['+0123 45 67 89', 'support@cart.com', 'Live Chat'];
        this.languages = ['FIN', 'ENG'];
        this.currencies = ['USD', 'AUD', 'GBP', 'EUR'];
    }
}
<div class='bar'>
    <div class='bar__content container clear-fix row'>
        <div class='bar__content--left col row'>
            <div class='language'>
                <div class='menu__dropdown'>
                    <a data-toggle='dropdown' href='#'>{{ languages[1] }}</a>
                    <span class='dropdown-toggle'></span>
                    <ul class='menu__dropdown--list'>
                        <li *ngFor="let language of languages">{{ language }}</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class='bar__content--right row'>
            <div class='options ml-auto row'>
                <div class='options__container col' *ngFor="let option of options">
                    <a href='#'>{{ option }}</a>
                </div>
            </div>
            <div class='currency ml-auto'>
                <select class='currency__select'>
                    <option *ngFor="let currency of currencies">{{ currency }}</option>
                </select>
                <span class='currency__span--toggle'></span>
            </div>
            <div class='help ml-auto'>
                <button class='help__button'>Customer Center</button>
            </div>
        </div>
    </div>
</div>
