// angular-app/src/app/menubar/menubar.component.ts
import { Component, Input } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

@Component({
    selector: 'menubar',
    templateUrl: './menubar.component.html',
    styleUrls: ['./menubar.component.css' ]
})
export class MenuComponent {
}
<div class='bar'>
    <div class='bar__content container clear-fix'>
      <nav class='menu navbar-toggleable-md'>

        <button class='navbar-toggler navbar-toggler-right collapsed' type='button'
          data-toggle='collapse' data-target='#navbarNav'
          aria-controls='navbarNav' aria-expanded='false' aria-label='Toggle navigation'>
          <span class='navbar-toggler-icon'></span>
        </button>

        <div class='navbar-collapse collapse' id='navbarNav' >
          <ul class='navbar-nav'>
            <li class='menu__content--item nav-item' routerLinkActive='active'>
              <a routerLink='/main' class='menu__content--link nav-link'> Main </a>
            </li>
            <li class='menu__content--item nav-item' routerLinkActive='active'>
              <a routerLink='/about' class='menu__content--link nav-link'> About </a>
            </li>
          </ul>
        </div>

      </nav>
    </div>
  </div>

// react-app/src/elements/components/MenuBar.js
import React from 'react';
import { NavLink } from 'react-router-dom'
import '../../css/components/MenuBar.css';

const MenuBar = () => {
    return (
        <div className='menu__bar'>
            <div className='menu__bar__content container clear-fix'>
                <nav className='menu navbar-toggleable-md'>

                    <button className='navbar-toggler navbar-toggler-right collapsed' type='button' data-toggle='collapse' data-target='#navbarNav'
                        aria-controls='navbarNav' aria-expanded='false' aria-label='Toggle navigation'>
                        <span className='navbar-toggler-icon'></span>
                    </button>

                    <div className='navbar-collapse collapse' id='navbarNav'>
                        <ul className='navbar-nav'>
                            <li className='menu__content--item nav-item'>
                                <NavLink exact to='/' className='menu__content--link nav-link' activeclassNameName="menu__content--link nav-link active">Main</NavLink>
                            </li>
                            <li className='menu__content--item nav-item'>
                                <NavLink to='/about' className='menu__content--link nav-link' activeclassNameName="menu__content--link nav-link active">About</NavLink>
                            </li>
                        </ul>
                    </div>

                </nav>
            </div>
        </div>
    );
  }

export default MenuBar;
