// react-app/src/elements/components/Product.js
import React from 'react';
import '../../css/components/Product.css';

class Product extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            imageUrl: '',
            subtitle: '',
            title: '',
            price: ''
        }
    }

    componentDidMount() {
        this.setState( { 
            imageUrl: this.props.imageUrl,
            subtitle: this.props.subtitle,
            title: this.props.title,
            price: this.props.price
        });
    }
    render() {
        return (
            <div className='product'>
                <article className='product__content'>
                    <img className='product__content--img' src={this.state.imageUrl} alt='' />
                    <span className='product__content--tag'>{this.state.subtitle}</span>
                    <a href='' className='product__content--title'>{this.state.title}</a>
                    <p className='product__content--review'>
                        <span className='margin-left-10'>5 Review(s)</span>
                    </p>
                    <div className='product__content--price'>{this.state.price}</div>
                    <a href='' className='product__content--cart'> </a>
                </article>
            </div>
        );
    }
}

export default Product;

// angular-app/src/app/product/product.component.ts
import { Component, Input } from '@angular/core';


@Component({
    selector: 'product',
    templateUrl: './product.component.html',
    styleUrls: ['./product.component.css' ]
})
export class ProductComponent {
    @Input() item: any = {};
    constructor() { }
}

<div class='product'>
  <article class='product__content'>
    <img class='product__content--img' src="{{item.imageUrl}}" alt=''>
    <span class='product__content--tag'>{{ item.subtitle }}</span>
    <a href='#' class='product__content--title'>{{ item.title }}</a>
    <p class='product__content--review'>
      <span class='margin-left-10'>5 Review(s)</span>
    </p>
    <div class='product__content--price'>{{item.price}}</div>
    <a href='#' class='product__content--cart'></a>
  </article>
</div>
